name: 'Docker-Coq Action'
branding:
  icon: 'check-circle'
  color: 'gray-dark'
description: 'GitHub Action using Docker-Coq'
author: 'Erik Martin-Dorel'
inputs:
  opam_file:
    description: 'The path of the .opam file (or a directory), relative to the repo root.'
    default: '.'
  coq_version:
    description: '"8.X", "latest", or "dev".'
    default: 'latest'
  ocaml_version:
    description: '"minimal", "4.XX", or "4.XX-flambda", see https://github.com/coq-community/docker-coq/wiki#supported-tags'
    default: 'minimal'
  before_install:
    description: 'Customizable script run before "install".'
    default: |
      startGroup "Print opam config"
        opam config list; opam repo list; opam list
      endGroup
  install:
    description: 'Customizable script to install the opam dependencies.'
    default: |
      startGroup "Install dependencies"
        opam pin add -n -y -k path $PACKAGE $WORKDIR
        opam update -y
        opam install -y -j 2 $PACKAGE --deps-only
      endGroup
  after_install:
    description: 'Customizable script run after "install".'
    default: |
      startGroup "List installed packages"
        opam list
      endGroup
  before_script:
    description: 'Customizable script run before the opam build, empty by default.'        
  script:
    description: 'Customizable script run to install the opam package(s).'
    default: |
      startGroup "Build"
        opam install -y -v -j 2 $PACKAGE
        opam list
      endGroup
  after_script:
    description: 'Customizable script run after the opam build, empty by default.'
  uninstall:
    description: 'Customizable script run to uninstall the opam package(s).'
    default: |
      startGroup "Uninstallation test"
        opam remove $PACKAGE
      endGroup
  custom_script:
    description: 'The main script run in the container; may be overridden.'
    default: |
      {{before_install}}
      {{install}}
      {{after_install}}
      {{before_script}}
      {{script}}
      {{after_script}}
      {{uninstall}}
  custom_image:
    description: 'The name of the Docker image to pull; unset by default.'
  export:
    description: 'Space-separated list of env variables to export to the custom_script.'
runs:
  using: 'docker'
  image: 'Dockerfile'
