name: 'Docker-Coq Action'
branding:
  icon: 'check-circle'
  color: 'gray-dark'
description: 'GitHub Action using Docker-Coq'
author: 'Erik Martin-Dorel'
inputs:
  opam_file:
    description: 'The path of the .opam file, relative to the repo root.'
    required: true
  coq_version:
    description: '"8.X", "latest", or "dev".'
    default: 'latest'
  ocaml_version:
    description: 'minimal, 4.07-flambda, or 4.09-flambda'
    default: 'minimal'
  custom_script:
    description: 'The main script run in the container; may be overridden.'
    default: |
      startGroup Print opam config
        opam config list; opam repo list; opam list
      endGroup
      startGroup Build dependencies
        opam pin add -n -y -k path $PACKAGE $WORKDIR
        opam update -y
        opam install -y -j 2 $PACKAGE --deps-only
      endGroup
      startGroup List installed packages
        opam list
      endGroup
      startGroup Build
        opam install -y -v -j 2 $PACKAGE
        opam list
      endGroup
      startGroup Uninstallation test
        opam remove $PACKAGE
      endGroup
  custom_image:
    description: 'The name of the Docker image to pull; unset by default.'
runs:
  using: 'docker'
  image: 'Dockerfile'
